//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int ID_EMPRESA { get; set; }
        public string CLASE_REGIMEN { get; set; }
        public string NIT { get; set; }
        public string DIG_VER { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string REP_LEGAL { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string TELEFONO1 { get; set; }
        public string ESTADO { get; set; }
    }
}
