//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class planillarecaudo
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Recorridos { get; set; }
        public Nullable<int> InicioTorniquete { get; set; }
        public Nullable<int> FinTorniquete { get; set; }
        public Nullable<int> NumPasajeros { get; set; }
        public Nullable<decimal> ProductoBruto { get; set; }
        public Nullable<decimal> ProductoNeto { get; set; }
        public Nullable<int> idDetallesPlanilla { get; set; }
    
        public virtual detallesplanilla detallesplanilla { get; set; }
        public virtual gastos gastos { get; set; }
    }
}
