//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutas
    {
        public rutas()
        {
            this.coordenadasrutas = new HashSet<coordenadasrutas>();
        }
    
        public string NomRuta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<int> Gabela { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> TiempoRecorrido { get; set; }
    
        public virtual ICollection<coordenadasrutas> coordenadasrutas { get; set; }
    }
}
