//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariosplataforma
    {
        public Nullable<int> Roll { get; set; }
        public string Contraseña { get; set; }
        public string User { get; set; }
    
        public virtual rolesusuariosplataforma rolesusuariosplataforma { get; set; }
    }
}
