//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentospersona
    {
        public int id { get; set; }
        public Nullable<int> documento { get; set; }
        public string cedula { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> fechaExpedicion { get; set; }
        public Nullable<System.DateTime> fechaExpiracion { get; set; }
    
        public virtual documentos documentos { get; set; }
        public virtual personas personas { get; set; }
    }
}
