//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gastos
    {
        public int idplanillarecaudo { get; set; }
        public Nullable<decimal> ACPM { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<decimal> Aseo { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<decimal> Turno { get; set; }
        public Nullable<decimal> TotalGasto { get; set; }
    
        public virtual planillarecaudo planillarecaudo { get; set; }
    }
}
