//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntoscontrolruta
    {
        public int id { get; set; }
        public string NomRuta { get; set; }
        public int Punto { get; set; }
    
        public virtual puntoscontrol puntoscontrol { get; set; }
        public virtual rutas rutas { get; set; }
    }
}
