//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutagrupo
    {
        public int id { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string Ruta { get; set; }
    
        public virtual gruposbuses gruposbuses { get; set; }
        public virtual rutas rutas { get; set; }
    }
}
